#!/usr/bin/env bash

# Fix array index for ZSH
if [[ $ZSH_NAME == "zsh" ]];then
  setopt localoptions ksharrays
fi

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

hook_path() {
  echo "$FUNL_HOOKS/$1"
}

is_hooked() {
  test -e "$FUNL_HOOKS/$1"
}

BANNED=(funl command)

is_banned() {
  for ban in ${BANNED[@]}; do
    if [[ $ban == $1 ]]; then
      return 0
    fi
  done
  return 1
}


# DATA STREAM MODULE

BUFFER=""

echo_to_pipe() {
  BUFFER="$BUFFER$1\n"
}

exit_with() {
  if [[ ! -z $opt_pipe ]]; then
    echo -e "$BUFFER" >"$opt_pipe/output"
    echo "$1" >"$opt_pipe/code"
  fi
  exit $1
}


# CACHE MODULE

CACHE=()

cache_clear() {
  local i=0
  for entry in ${CACHE[@]}; do
    if [[ $entry =~ "$1=" ]]; then
      unset -v "CACHE[$i]"
      return 0
    fi
    (( i ++ ))
  done
  return 1
}

cache_set() {
  cache_clear "$1"
  CACHE+=( "$1=$2" )
  return 0
}

cache_get() {
  for entry in ${CACHE[@]}; do
    if [[ $entry =~ "$1=" ]]; then
      echo "$(echo $entry | awk -F= '{ print $2 }')"
      return 0
    fi
  done
  return 1
}
