#!/usr/bin/env bash

DESC=$(cat <<TEXT
Usage: funl config

Show available placeholder and alias names.
TEXT
)

if [[ 3 -le $# ]]; then
  exit 1
fi

if [[ 1 -eq $# ]]; then
  if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
    echo -e "$DESC"
    exit 0
  else
    exit 1
  fi
fi

if [[ -z $FUNL_CONFIG ]]; then
  FUNL_CONFIG="$HOME/.funlrc"
fi

if [[ ! -e $FUNL_CONFIG ]]; then
  echo "funl: config not found" >&2
  exit 1
fi

if [[ 0 -eq $# ]]; then
  names=()
  placeholders="$(cat "$FUNL_CONFIG" | grep -o '[ ]*.*.src[ ]*:' | sed -e 's/.src[ ]*://' | sed 's/[ ]//g' | sort)"
  for name in "$placeholders"; do
    names+=( "$name" )
  done
  aliases="$(cat "$FUNL_CONFIG" | grep -o '[ ]*.*[ ]*:[ ]*&' | sed -e 's/[ ]*:[ ]*&//' | sed 's/[ ]//g' | sort)"
  for name in "$aliases"; do
    names+=( "$name" )
  done
  echo ${names[@]}
  exit 0
fi

# Find alias
alias=$(cat "$FUNL_CONFIG" | grep -E "[ ]*$1[ ]*:[ ]*&" | grep -oE '&[[:alnum:]_-]+' | sed 's/&//g' | head -n 1)
if [[ $alias ]]; then
  name="$alias"
else
  name="$1"
fi

# Find definition
line=$(cat "$FUNL_CONFIG" | grep -E "^$name\\.$2 *:" | head -n 1)
if [[ -z $line ]]; then
  case "$2" in
    # required
    src )
      echo "funl: '$name.$2' definition not found" >&2
      exit 1
      ;;
    # optional
    post )
      exit 0
      ;;
    # invalid type
    * )
      echo "funl: invalid type: '$2'" >&2
      exit 1
      ;;
  esac
fi

line=$(echo "$line" | sed -e "s/$name.$2 *: *//")

echo "$line"
