#!/usr/bin/env bash

set -e

content=$(cat <<HELP
Usage: funl <command> [...]

Here are available commands:

     list: List all registered hook names
     hook: Register a hook of the given executable
   unhook: Unregister a hook
  version: Show version information
     help: Displays help contents

Use 'funl help <command>' for more information of specific command.
HELP
)

shift
if [[ ! -z $1 ]]; then
  content=$(funl $1 -h)
  if [[ 0 -ne $? ]]; then
    echo "$content" >&2
    exit 1
  fi
fi

echo -e "$content"
