#!/usr/bin/env bash

set -e

DESC=$(cat <<TEXT
Usage: funl unhook [-e] <name>...

Unregisters hooks of the given names.
TEXT
)

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

if [[ 0 -eq $# ]]; then
  echo -e "$DESC" >&2
  exit 1
fi

names=()
opt_eval=0
while [[ $1 ]]; do
  if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
    echo -e "$DESC"
    exit 0
  fi

  if [[ $1 == '-e' ]]; then
    opt_eval=1
    shift
    continue
  fi

  hook_path="$FUNL_HOOKS/$1"
  if [[ ! -e $hook_path ]]; then
    [[ -n $FUNL_DEBUG ]] && echo "funl: '$1' isn't registered as hook" >&2
    shift
    continue
  fi

  names+=( "$1" )

  shift
done

if [[ 0 -eq ${#names[@]} ]]; then
  echo -e "$DESC" >&2
  exit 1
fi

for name in ${names[@]}; do
  hook_path="$FUNL_HOOKS/$name"
  rm -f "$hook_path"

  if [[ $opt_eval -eq 1 ]]; then
    echo -e "$(funl feed undef $name)"
  fi
done
