#!/usr/bin/env bash

path_remove() {
  local paths=$PATH
  while [[ 0 -lt $# ]]
  do
    paths=$(echo -n $paths | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//')
    shift
  done
  echo "$paths"
}

shift
if [[ 0 -eq $# ]]; then
  exit 1
fi

bin_dir="$FUNL_ROOT/bin"

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

new_path=$(path_remove "$bin_dir" "$FUNL_HOOKS")

# echo "EXEC: $#: $@"
# echo "EXEC: $1 | $2 | $3 | $4 | $5 | $6"

PATH=$new_path exec "$@"
