#!/usr/bin/env bash

shift
if [[ 1 -ne $# ]]; then
  exit 1
fi

src=$(funl config "$1" "src")
if [[ 0 -ne $? ]]; then
  exit 1
fi

# TODO: Support both peco and percol (self-modifying for speed?)
selected=$(eval "$src | peco")
if [[ 0 -ne $? ]]; then
  exit 1
fi

echo "$selected"
