#!/usr/bin/env bash

shift
if [[ 0 -eq $# ]]; then
  exit 1
fi

i=0
params=
for param in "$@"; do
  name=$(echo "$param" | sed -e 's/^[^{]*{\([^}][^}]*\)}[^}]*$/\1/')

  if [[ $name == $param ]]; then
    params[$i]="$param"
  else
    choice=$(funl select "$name")
    if [[ 0 -ne $? ]]; then
      exit 1
    fi

    choice=$(funl post-proc "$name" "$choice")
    if [[ 0 -ne $? ]]; then
      echo "funl: error occured in post-process '$name.post'" >&2
      exit 1
    fi

    script="s;{$name};$choice;g"
    params[$i]=$(echo "$param" | sed "$script")
  fi

  (( i ++ ))
done

set -- "${params[@]}"

exec funl exec "$@"
