#!/usr/bin/env bash

set -e

content=$(cat <<HELP
Usage: funl hook <name>

Registers a hook of the given executable, such as builtin command,
program, and shell script.
HELP)

shift
if [[ 0 -eq $# ]]; then
  echo -e "$content" >&2
  exit 1
fi

if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
  echo -e "$content"
  exit 0
fi

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

if [[ ! -d $FUNL_HOOKS ]]; then
  mkdir -p "$FUNL_HOOKS"
fi

hook_path="$FUNL_HOOKS/$1"
if [[ -e $hook_path ]]; then
  echo "funl: '$1' is already hooked" >&2
  exit 1
fi

cat <<SH > "$hook_path"
#!/usr/bin/env bash

# XXX: Should I wrap \$1 with double-quotes?
exec funl proc $1 "\$@"
SH

chmod a+x "$hook_path"
