#!/usr/bin/env bash

version='0.0.0'

pushd "$FUNL_ROOT" >/dev/null 2>&1
rev=$(git rev-parse --short HEAD 2>/dev/null)
popd >/dev/null 2>&1

if [[ ! -z $rev ]]; then
  version="$version-$rev"
fi

echo "funl $version"
