#!/usr/bin/env bash

set -e

content=$(cat <<HELP
Usage: funl hook [-e] <name>...

Registers hooks of the given executable, such as builtin command,
program, and shell script.

'-e' option is useful to enable hooked command right now.
e.g. $ eval "\$(funl hook -e git)"
HELP
)

shift
if [[ 0 -eq $# ]]; then
  echo -e "$content" >&2
  exit 1
fi

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

output=""
while [[ $1 ]]; do
  if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
    echo -e "$content"
    exit 0
  fi

  if [[ $1 == '-e' ]]; then
    output="yes"
    shift
    continue
  fi

  hook_path="$FUNL_HOOKS/$1"
  if [[ -e $hook_path ]]; then
    echo "funl: '$1' is already hooked" >&2
    exit 1
  fi

  cat <<SH > "$hook_path"
# funl hook file for '$1' command
SH

  if [[ $output == 'yes' ]]; then
    echo -e "$(funl rehash --def $1)"
  fi

  shift
done
