#!/usr/bin/env bash

path_remove() {
  local paths=$PATH
  while [[ 0 -lt $# ]]
  do
    paths=$(echo -n $paths | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//')
    shift
  done
  echo $paths
}

shift
if [[ 0 -eq $# ]]; then
  exit 1
fi

bin_dir=$(dirname $(command which funl))
hooks_dir="$(dirname $bin_dir)/hooks"
new_path=$(path_remove $bin_dir $hooks_dir)

# echo "EXEC: $#: $@"
# echo "EXEC: $1 | $2 | $3 | $4 | $5 | $6"

PATH=$new_path exec "$@"
