#!/usr/bin/env bash

DESC=$(cat <<TEXT
Usage: funl list [-1]

Lists all registered hook names.
In case of no registered hooks, this command prints nothing.
If '-1' option is specified, funl lists one name per one line.
TEXT
)

opt_one=0
while [[ $1 ]]; do
  if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
    echo -e "$DESC"
    exit 0
  fi

  if [[ $1 == '-1' ]]; then
    opt_one=1
    break
  fi

  shift
done

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

if [[ $opt_one -eq 1 ]]; then
  ls_opt='-1'
else
  ls_opt='-m'
fi

hooks=$(command ls "$ls_opt" "$FUNL_HOOKS")
if [[ ! -z $hooks ]]; then
  echo -e "$hooks"
fi
