#!/usr/bin/env bash

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

if [[ ! -d $FUNL_HOOKS ]]; then
  command mkdir -p "$FUNL_HOOKS"
fi

cat <<SH
#!/usr/bin/env bash

funl() {
  local funl_path="$FUNL_ROOT/bin/funl"
  case "\$1" in
    hook | unhook )
      local cmd="\$1"
      shift

      local base="\$(\$funl_path pipe)"
      ("\$funl_path" "\$cmd" "--pipe=\$base" "\$@" &)

      local output="\$(cat \$base/output)"
      local code="\$(cat \$base/code)"

      "\$funl_path" pipe -d "\$base"

      eval "\$output"
      return \$code
      ;;
    * )
      "\$funl_path" "\$@"
      ;;
  esac
}
SH

funcs="$(funl feed def)"
if [[ ! -z $funcs ]]; then
  echo -e "$funcs"
fi
