#!/usr/bin/env bash

path_remove() {
  local paths=$PATH
  while [[ 0 -lt $# ]]; do
    paths=$(echo -n $paths | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//')
    shift
  done
  echo "$paths"
}

if [[ 0 -eq $# ]]; then
  [[ -n $FUNL_DEBUG ]] && echo "funl-exec: no arguments" >&2
  exit 1
fi

bin_dir="$FUNL_ROOT/bin"
new_path=$(path_remove "$bin_dir")

$(PATH=$new_path type $1 >/dev/null 2>&1)
if [[ 0 -ne $? ]]; then
  echo "funl: command not found: $1" >&2
  exit 1
fi

PATH=$new_path exec "$@"
