#!/usr/bin/env bash

shift
if [[ 0 -eq $# ]]; then
  exit 1
fi

# TODO: Support both peco and percol (self-modifying for speed?)
selected=$(git for-each-ref --sort=-committerdate refs/heads/ | cut -f2 | sed 's/refs\/heads\///g' | peco)

if [[ 0 -ne $? ]]; then
  exit $?
fi

echo -e "$selected"
