#!/usr/bin/env bash

shift
if [[ 0 -eq $# ]]; then
  exit 1
fi

# TODO: Support multiple placeholders
params="$@"
name=$(echo "$@" | sed -e 's/^[^{]*{\([^}][^}]*\)}[^}]*$/\1/')

if [[ $params != $name ]]; then
  selected=$(funl select $name)

  if [[ 0 -ne $? ]]; then
    echo "funl: not selected, abort" >&2
    exit $?
  fi

  script="s|{$name}|$selected|"
  params=$(echo "$@" | sed "$script")
fi

exec funl exec $params
