#!/usr/bin/env bash

FUNL_BANNED=(funl command)

is_banned() {
  for ban in ${FUNL_BANNED[@]}; do
    if [[ $ban == $1 ]]; then
      return 0
    fi
  done
  return 1
}

def_func() {
  echo "$1() { funl proc $1 \"\$@\" ; }"
}

undef_func() {
  echo "unset -f \"$1\" >/dev/null 2>&1 || true"
}

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

case "$2" in
"--def" )
  echo -e "$(def_func $3)"
  ;;
"--undef" )
  echo -e "$(undef_func $3)"
  ;;
* )
  IFS=', '
  for name in $(command ls -m "$FUNL_HOOKS"); do
    if is_banned $name; then
      continue
    fi
    echo -e "$(def_func $name)"
  done
  ;;
esac
