#!/usr/bin/env bash

set -e

content=$(cat <<HELP
Usage: funl unhook <name>

Unregisters a hook of the given name.
HELP
)

shift
if [[ 0 -eq $# ]]; then
  echo -e "$content" >&2
  exit 1
fi

if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
  echo -e "$content"
  exit 0
fi

if [[ -z $FUNL_HOOKS ]]; then
  FUNL_HOOKS="$FUNL_ROOT/hooks"
fi

hook_path="$FUNL_HOOKS/$1"

if [[ ! -e $hook_path ]]; then
  echo "funl: '$1' isn't registered as hook" >&2
  exit 1
fi

rm -f "$hook_path"
