#!/usr/bin/env bash

if [[ 2 -ne $# ]]; then
  [[ -n $FUNL_DEBUG ]] && echo "funl-post-proc: no arguments" >&2
  exit 1
fi

post=$(funl config "$1" "post")
if [[ 0 -ne $? ]]; then
  [[ -n $FUNL_DEBUG ]] && echo "funl-post-proc: failed in funl-config: $1: $post" >&2
  exit 1
fi

if [[ -z $post ]]; then
  echo "$2"
  exit 0
fi

processed=$(eval "echo \"$2\" | $post" 2>&1)
if [[ 0 -ne $? ]]; then
  [[ -n $FUNL_DEBUG ]] && echo "funl-post-proc: failed in post-proc: $processed" >&2
  exit 1
fi

echo "$processed"
