#!/usr/bin/env bash

if [[ 2 -ne $# ]]; then
  [[ -n $FUNL_DEBUG ]] && echo "funl-config: accepts 2 params, but $#" >&2
  exit 1
fi

if [[ -z $FUNL_CONFIG ]]; then
  FUNL_CONFIG="$HOME/.funlrc"
fi

if [[ ! -e $FUNL_CONFIG ]]; then
  echo "funl: config not found" >&2
  exit 1
fi

line=$(cat "$FUNL_CONFIG" | grep -E "^$1\\.$2 *:" | head -n 1)
if [[ -z $line ]]; then
  if [[ $2 == "src" ]]; then
    # 'src' definition is required
    echo "funl: 'src' definition is required (missing '$1.$2')" >&2
    exit 1
  else
    # other ('post', ...) definitions are optional
    exit 0
  fi
fi

line=$(echo "$line" | sed -e "s/$1.$2 *: *//")

echo "$line"
