#!/usr/bin/env bash

version='0.0.0'

pushd "$FUNL_ROOT" >/dev/null 2>&1
rev=$(git describe --tags 2>/dev/null)
if [[ 0 -ne $? ]]; then
  rev=$(git rev-parse --short HEAD 2>/dev/null)
fi
popd >/dev/null 2>&1

if [[ $rev ]]; then
  version="$rev"
fi

echo "funl $version"
