#!/usr/bin/env bash

if [[ 0 -eq $# ]]; then
  [[ -n $FUNL_DEBUG ]] && echo "funl-proc: no arguments" >&2
  exit 1
fi

params=()
for param in "$@"; do
  name=$(echo "$param" | grep -o '{\w\+}' | sed -e 's/[{}]//g')
  if [[ -z $name ]]; then
    params+=( "$param" )
  else
    choice=$(funl select "$name")
    if [[ 0 -ne $? ]]; then
      exit 1
    fi

    choice=$(funl post-proc "$name" "$choice")
    if [[ 0 -ne $? ]]; then
      echo "funl: error occured in post-process '$name.post'" >&2
      exit 1
    fi

    script="s;{$name};$choice;g"
    params+=( "$(echo "$param" | sed "$script")" )
  fi
done

set -- "${params[@]}"

exec funl exec "$@"
