#!/usr/bin/env bash

set -e

shift

if [[ 0 -eq $# ]]; then
  echo "usage: funl hook <name>" >&2
  echo "e.g. git, ssh, kill" >&2
  exit 1
fi

hooks_dir="$(dirname $(dirname $(command which funl)))/hooks"


if [[ ! -d $hooks_dir ]]; then
  mkdir $hooks_dir
fi

hook_path="$hooks_dir/$1"

if [[ -e $hook_path ]]; then
  echo "funl: '$1' is already hooked" >&2
  exit 1
fi

cat << EOS > "$hook_path"
#!/usr/bin/env bash

exec funl proc $1 \$@
EOS

chmod a+x "$hook_path"
